In [1]:
###import important modules

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
##read data and print top-5 rows

data = pd.read_csv("archive/food_coded.csv", delimiter=',')
data.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

In [13]:
###get the information/details of the dataset like total values, data type, and the shape of the complete dataset
### which is rows*cols - 125*61 here
print(data.info())
print(data.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
GPA                             123 non-null object
Gender                          125 non-null int64
breakfast                       125 non-null int64
calories_chicken                125 non-null int64
calories_day                    106 non-null float64
calories_scone                  124 non-null float64
coffee                          125 non-null int64
comfort_food                    124 non-null object
comfort_food_reasons            124 non-null object
comfort_food_reasons_coded      106 non-null float64
cook                            122 non-null float64
comfort_food_reasons_coded.1    125 non-null int64
cuisine                         108 non-null float64
diet_current                    124 non-null object
diet_current_coded              125 non-null int64
drink                           123 non-null float64
eating_changes                  122 non-null object
eating_changes_coded            125 non-null int64
eating_changes_coded1           125 non-null int64
eating_out                      125 non-null int64
employment                      116 non-null float64
ethnic_food                     125 non-null int64
exercise                        112 non-null float64
father_education                124 non-null float64
father_profession               122 non-null object
fav_cuisine                     123 non-null object
fav_cuisine_coded               125 non-null int64
fav_food                        123 non-null float64
food_childhood                  124 non-null object
fries                           125 non-null int64
fruit_day                       125 non-null int64
grade_level                     125 non-null int64
greek_food                      125 non-null int64
healthy_feeling                 125 non-null int64
healthy_meal                    124 non-null object
ideal_diet                      124 non-null object
ideal_diet_coded                125 non-null int64
income                          124 non-null float64
indian_food                     125 non-null int64
italian_food                    125 non-null int64
life_rewarding                  124 non-null float64
marital_status                  124 non-null float64
meals_dinner_friend             122 non-null object
mother_education                122 non-null float64
mother_profession               123 non-null object
nutritional_check               125 non-null int64
on_off_campus                   124 non-null float64
parents_cook                    125 non-null int64
pay_meal_out                    125 non-null int64
persian_food                    124 non-null float64
self_perception_weight          124 non-null float64
soup                            124 non-null float64
sports                          123 non-null float64
thai_food                       125 non-null int64
tortilla_calories               124 non-null float64
turkey_calories                 125 non-null int64
type_sports                     104 non-null object
veggies_day                     125 non-null int64
vitamins                        125 non-null int64
waffle_calories                 125 non-null int64
weight                          123 non-null object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.6+ KB
None
(125, 61)

In [14]:
data.describe()   ###statistical analysis of the dataset

,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,...,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,veggies_day,vitamins,waffle_calories
count,125.000000,125.000000,125.000000,106.000000,124.000000,125.00000,106.000000,122.000000,125.000000,108.000000,...,124.000000,124.000000,124.000000,123.000000,125.000000,124.000000,125.000000,125.000000,125.000000,125.000000
mean,1.392000,1.112000,577.320000,3.028302,505.241935,1.75200,2.698113,2.786885,2.688000,1.388889,...,2.806452,3.120968,1.217742,1.390244,3.336000,947.580645,555.040000,4.008000,1.512000,1073.400000
std,0.490161,0.316636,131.214156,0.639308,230.840506,0.43359,1.972042,1.038351,1.910987,0.974759,...,1.423824,1.115980,0.414385,0.489800,1.436528,202.090179,152.370379,1.081337,0.501867,248.667092
min,1.000000,1.000000,265.000000,2.000000,315.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,580.000000,345.000000,1.000000,1.000000,575.000000
25%,1.000000,1.000000,430.000000,3.000000,420.000000,2.00000,2.000000,2.000000,2.000000,1.000000,...,2.000000,2.000000,1.000000,1.000000,2.000000,725.000000,500.000000,3.000000,1.000000,900.000000
50%,1.000000,1.000000,610.000000,3.000000,420.000000,2.00000,2.000000,3.000000,2.000000,1.000000,...,3.000000,3.000000,1.000000,1.000000,3.000000,940.000000,500.000000,4.000000,2.000000,900.000000
75%,2.000000,1.000000,720.000000,3.000000,420.000000,2.00000,3.000000,3.000000,3.000000,1.000000,...,4.000000,4.000000,1.000000,2.000000,5.000000,1165.000000,690.000000,5.000000,2.000000,1315.000000
max,2.000000,2.000000,720.000000,4.000000,980.000000,2.00000,9.000000,5.000000,9.000000,6.000000,...,5.000000,6.000000,2.000000,2.000000,5.000000,1165.000000,850.000000,5.000000,2.000000,1315.000000

In [17]:
data.isnull().sum()  ###check for the null values and take their sum

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             1
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
                                ..
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     21
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
Length: 61, dtype: int64

In [12]:
###draw the various plots to understand the data distribution